export const EntityImages: Record<string, string> = {
    Archer: '/assets/characters/attacks/Archer_Attack.png',
    Archer_Death: '/assets/characters/deaths/Archer_Death.png',
    Cleric: '/assets/characters/attacks/Cleric_Attack.png',
    Cleric_Death: '/assets/characters/deaths/Cleric_Death.png',
    Knight: '/assets/characters/attacks/Knight_Attack.png',
    Knight_Death: '/assets/characters/deaths/Knight_Death.png',
    Mage: '/assets/characters/attacks/Mage_Attack.png',
    Mage_Death: '/assets/characters/deaths/Mage_Death.png',
    Monk: '/assets/characters/attacks/Monk_Attack.png',
    Monk_Death: '/assets/characters/deaths/Monk_Death.png',
    Rogue: '/assets/characters/attacks/Rogue_Attack.png',
    Rogue_Death: '/assets/characters/deaths/Rogue_Death.png',
    Shaman: '/assets/characters/attacks/Shaman_Attack.png',
    Shaman_Death: '/assets/characters/deaths/Shaman_Death.png',
    Warrior: '/assets/characters/attacks/Warrior_Attack.png',
    Warrior_Death: '/assets/characters/deaths/Warrior_Death.png',
    Death_Knight: '/assets/enemies/Death_Knight.png',
    Ent: '/assets/enemies/Ent.png',
    Ettin: '/assets/enemies/Ettin.png',
    Goblin: '/assets/enemies/Goblin.png',
    Ghoul: '/assets/enemies/Ghoul.png',
    Manticore: '/assets/enemies/Manticore.png',
    Rat: '/assets/enemies/Rat.png',
    Skeleton: '/assets/enemies/Skeleton.png',
    Zombie: '/assets/enemies/Zombie.png',
};